spring:
  application:
    name: MSV-APIGATEWAY  
  cloud:
    gateway:
      routes:
        - id: MSV-USERSSERVICE
          uri: lb://MSV-USERSSERVICE
          predicates:
            - Path=/user/**
        - id: MSV-HOTELSSERVICE
          uri: lb://MSV-HOTELSSERVICE
          predicates:
            - Path=/hotel/**
        - id: MSV-RATINGSSERVICE
          uri: lb://MSV-RATINGSSERVICE
          predicates:
            - Path=/rating/**

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
